import { chromium, _electron as electron } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const base = process.env.WAGECLAW_QA_URL || 'http://127.0.0.1:5174';
await mkdir('qa-shots', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome' });
const context = await browser.newContext({ viewport: { width: 1120, height: 750 }, timezoneId: 'Asia/Shanghai' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.clock.setFixedTime(new Date('2026-09-15T14:38:42+08:00'));
await page.goto(base);
await page.getByRole('heading', { name: '从你的工资和作息开始' }).waitFor();
await page.getByLabel('月薪', { exact: true }).fill('18000');
await page.getByLabel('春节放假开始', { exact: true }).fill('2027-02-01');
await page.getByLabel('春节放假结束（选填）', { exact: true }).fill('2027-02-10');
await page.getByLabel('年终奖预计发放日期', { exact: true }).fill('2027-01-29');
await page.getByLabel('预计金额（元，选填）', { exact: true }).fill('30000');
await page.getByRole('button', { name: '开始我的倒计时' }).click();
await page.getByRole('dialog').waitFor({ state: 'hidden' });
assert.equal(await page.getByTestId('offwork').textContent(), '03:21:18');
const income = await page.getByTestId('today-income').textContent();
await page.screenshot({ path: 'qa-shots/lite-home.png', fullPage: true });
assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollHeight <= globalThis.innerHeight));
await page.reload();
assert.equal(await page.getByTestId('today-income').textContent(), income);
await page.getByRole('button', { name: '隐藏金额', exact: true }).click();
assert.match(await page.getByTestId('today-income').textContent(), /••••/);
assert.match(await page.getByTestId('month-income').textContent(), /••••/);
assert.ok(!(await page.locator('main').innerText()).includes('30,000'));
await page.reload();
await page.getByRole('button', { name: '显示金额', exact: true }).click();
await page.getByRole('button', { name: '设置', exact: true }).click();
await page.screenshot({ path: 'qa-shots/lite-settings.png' });
await page.getByLabel('深色外观', { exact: true }).check();
await page.getByRole('button', { name: '保存设置' }).click();
await page.screenshot({ path: 'qa-shots/lite-dark.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'qa-shots/lite-narrow.png', fullPage: true });
assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth));
await page.getByRole('button', { name: '设置', exact: true }).click();
await page.getByLabel('下班时间', { exact: true }).fill('08:00');
await page.getByRole('button', { name: '保存设置' }).click();
assert.match(await page.getByRole('alert').textContent(), /跨夜/);
await page.getByRole('button', { name: '关闭设置' }).click();
await page.clock.setFixedTime(new Date('2026-09-15T19:00:00+08:00'));
await page.evaluate(() => globalThis.dispatchEvent(new Event('focus')));
assert.equal(await page.getByTestId('offwork').textContent(), '今天收工了');
await page.clock.setFixedTime(new Date('2026-09-19T12:00:00+08:00'));
await page.evaluate(() => globalThis.dispatchEvent(new Event('focus')));
assert.equal(await page.getByTestId('offwork').textContent(), '今天休息');
assert.equal(await page.getByTestId('today-income').textContent(), '¥ 0.00');
await page.getByRole('button', { name: '设置', exact: true }).click();
const download = page.waitForEvent('download');
await page.getByRole('button', { name: '导出备份', exact: true }).click();
assert.match((await download).suggestedFilename(), /wageclaw-backup/);
await page.getByRole('button', { name: '恢复默认设置', exact: true }).click();
await page.getByRole('button', { name: '确认重置并保留备份', exact: true }).click();
await page.getByRole('heading', { name: '从你的工资和作息开始' }).waitFor();
assert.ok(await page.evaluate(() => Object.keys(localStorage).some(key => key.includes(':backup:'))));
await page.evaluate(() => localStorage.setItem('wageclaw-lite-v1:local', '{broken'));
await page.reload();
await page.getByRole('button', { name: '开始我的倒计时' }).waitFor();
assert.equal(await page.getByRole('button', { name: '开始我的倒计时' }).isDisabled(), true);
assert.equal(await page.evaluate(() => localStorage.getItem('wageclaw-lite-v1:local')), '{broken');
await page.getByRole('button', { name: '恢复默认设置', exact: true }).click();
await page.getByRole('button', { name: '确认重置并保留备份', exact: true }).click();
assert.equal(await page.getByRole('button', { name: '开始我的倒计时' }).isEnabled(), true);
assert.deepEqual(errors, []);
await browser.close();
console.log('Browser: onboarding, countdown, persistence, privacy, dark/narrow layout, validation, after-work/rest states, export, reset and corrupt archive recovery passed.');
if (process.env.WAGECLAW_QA_ELECTRON === '1') {
  const env = { ...process.env, WAGECLAW_DEV_SERVER_URL: base }; delete env.ELECTRON_RUN_AS_NODE;
  // 普通终端无需关闭 Chromium 沙箱；受限环境（容器/沙箱）里设置 WAGECLAW_QA_NO_SANDBOX=1。
  const liteArgs = ['electron/main.cjs', `--user-data-dir=/tmp/wageclaw-lite-qa-${Date.now()}`];
  if (process.env.WAGECLAW_QA_NO_SANDBOX === '1') liteArgs.push('--no-sandbox');
  const app = await electron.launch({ args: liteArgs, env });
  try {
    const main = await app.waitForEvent('window', { predicate: win => win.url().includes('view=main') });
    await main.waitForLoadState('domcontentloaded');
    await main.getByLabel('月薪', { exact: true }).fill('18000');
    await main.getByLabel('春节放假开始', { exact: true }).fill('2027-02-01');
    await main.getByLabel('年终奖预计发放日期', { exact: true }).fill('2027-01-29');
    await main.getByRole('button', { name: '开始我的倒计时' }).click();
    const pet = app.windows().find(win => win.url().includes('view=pet')) || await app.waitForEvent('window', { predicate: win => win.url().includes('view=pet') });
    await pet.waitForLoadState('domcontentloaded');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().includes('view=pet'))?.isAlwaysOnTop()), true);
    await pet.screenshot({ path: resolve('qa-shots/lite-pet.png') });
    console.log('Electron: local onboarding, pet window creation, pinning and post-onboarding workflow passed.');
  } finally { await app.close(); }
}
